on:
  push:
    branches: [main]

name: Build and Release Extension

jobs:
  build:
    name: Build and Release Sounds Extension
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v2
      
      - name: Restore NuGet Packages
        run: nuget restore PlayniteSounds.sln
        timeout-minutes: 5
  
      - name: Build Extension
        run: msbuild PlayniteSounds.sln /p:Configuration=Release
        timeout-minutes: 10
      
      - name: Generate Version Info
        id: version
        run: |
          $timestamp = Get-Date -Format "yyyy.MM.dd.HHmm"
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $version = "build-$timestamp-$shortSha"
      
      - name: Setup Playnite Toolbox
        run: |
          mkdir playnite
          Write-Host "Downloading Playnite toolkit..."
          Invoke-WebRequest -Uri "https://github.com/JosefNemec/Playnite/releases/download/9.16/Playnite916.zip" -OutFile "playnite\Playnite916.zip"
          Write-Host "Extracting Playnite toolkit..."
          Expand-Archive "playnite\playnite916.zip" -DestinationPath "playnite"
        timeout-minutes: 5
      
      - name: Package Extension
        id: package
        run: |
          mkdir release
          Write-Host "Packaging extension..."
          playnite\toolbox.exe pack "bin\release" "release"
          
          $pextFile = Get-ChildItem -Path "release" -Filter "*.pext" | Select-Object -First 1
          if (-not $pextFile) {
            Write-Error "No .pext file was created!"
            exit 1
          }
          
          $fullPath = $pextFile.FullName
          $fileName = $pextFile.Name
          Write-Host "Created package: $fileName"
          
          echo "PEXTFILE=$fullPath" >> $env:GITHUB_ENV
          echo "PEXTNAME=$fileName" >> $env:GITHUB_ENV
        timeout-minutes: 2
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: PlayniteSounds ${{ env.VERSION }}
          body: |
            ## PlayniteSounds Extension - Automated Build
            
            This is an automated build of the PlayniteSounds extension.
            
            ### Build Information
            - **Commit:** ${{ github.sha }}
            - **Branch:** ${{ github.ref_name }}
            - **Build Date:** ${{ github.event.head_commit.timestamp }}
            - **Trigger:** Push to main branch
            
            ### Installation Instructions
            1. Download the `.pext` file below
            2. Open Playnite
            3. Go to Extensions → Install Extension
            4. Select the downloaded `.pext` file
            5. Restart Playnite
            
            ### What's New
            This build includes all changes from commit [${{ github.sha }}](${{ github.event.head_commit.url }}).
          files: ${{ env.PEXTFILE }}
          prerelease: true
          generate_release_notes: false
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
